### ISSUE TITLE
How to start with ?

### ISSUE THREAD

**Issue by ronea23** [waarp/WaarpR66#167]
Hi,
Can anyone help me with how to start with, the R66 Server becoz the defined procedures on the site.. did not work much.

Product features are outstanding, but when i try to run no success.

For e.g, the Golden Gate Password, which jar needs to be launched or it is the part of Server UI ?

If its the part of Server UI, how to launch the server UI.

And DATABASE initialization, ServerInitDatabase is a class in WaarpR66.x.x.x .jar,, but with what parameters it needs to be called ?

Can we have a standard working procedure to bring up the server ?

Have modified all the xml files, but still issue persists.

The repeated messages what I see is the following from the R66 Server log

Regards,
Ronald

**Comment by ronea23** [comment]
Pls see the below messages,

18/08/2015/10:40:40.942 WARN [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.loadServerParam(FileBasedConfiguration.java:1007) : Multiple Monitor configuration active for 2 servers in HA behind a Load Balancer in TCP
18/08/2015/10:40:40.964 WARN [org.waarp.openr66.context.authentication.R66Auth] [main] org.waarp.openr66.context.authentication.R66Auth.getServerAuth(R66Auth.java:245) : Cannot find the authentication SST24
org.waarp.common.database.exception.WaarpDatabaseNoDataException: No row found
	at org.waarp.openr66.database.data.DbHostAuth.select(DbHostAuth.java:508) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.database.data.DbHostAuth.<init>(DbHostAuth.java:365) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.context.authentication.R66Auth.getServerAuth(R66Auth.java:243) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2258) [WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.server.R66Server.initialize(R66Server.java:72) [WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.server.R66Server.main(R66Server.java:54) [WaarpR66-3.0.4.jar:na]
18/08/2015/10:40:40.966 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2262) : Cannot find Authentication for current host
18/08/2015/10:40:40.966 ERROR [org.waarp.openr66.server.R66Server] [main] org.waarp.openr66.server.R66Server.initialize(R66Server.java:74) : Needs a correct configuration file as first argument
18/08/2015/10:40:40.966 ERROR [org.waarp.openr66.server.R66Server] [main] org.waarp.openr66.server.R66Server.main(R66Server.java:58) : Cannot start Server OpenR66 for SST24


Pls help.

Regards,
Ronald

**Comment by fredericBregier** [comment]
@ronea23 
You'll find in the zip directories for Linux and Windows, containing the script files: 

     /bin/Linux => see ENV_R66 and below directory bin and in particular r66command.sh
     /bin/Windows => see bin directory and in particular setvari.bat (similar to ENV_R66 for Windows)

Have a look then to the web page for command lnes: http://waarp.github.io/Waarp/WaarpR66CommandLine.html

For the GoldenGate Password, see here http://waarp.github.io/Waarp/Password.html
You can create your own command (as in ENV_R66 or setvari.bat) to launch the GG Password (class name = `org.waarp.uip.WaarpUiPassword` )

You can also use the Gui Administrator in the very same way (including the GG Password): main class = `org.waarp.administrator.AdminGui` which needs at least one R66 configuration file (default one could do the trick for starting before replacing with a real one).

And for the configuration, please follow there: http://waarp.github.io/Waarp/WaarpR66Configuration.html

**Comment by ronea23** [comment]
Hi,
I tried to run the same command lines, but it gives me "wrong initialization" error.

How to launch the GG password GUI.??
No clue the server launch is failing.

I know i am missing something, but let me know ,, on windows what shud be the command to initialize the server.

"C:\SST24\WARP\bin\Windows\bin>server.bat" this is the command i invoke.

Regards,
Ronald

**Comment by ronea23** [comment]
i have modified the setvari according to my local machine.

REM JDK SUN
SET JAVA_OPTS1=-server
SET JAVA_OPTS2=-Xms256m -Xmx1024m
REM SET JAVA_RUN="C:\Program Files\Java\jdk1.6.0_14\jre\bin\java" %JAVA_OPTS1% %JAVA_OPTS2% 
SET JAVA_7HOME="C:\Program Files (x86)\Java\jdk1.7.0_55\jre\bin"
SET JAVA_RUN=%JAVA_7HOME%\java %JAVA_OPTS1% %JAVA_OPTS2% 
REM SET JAVASERVER_RUN="C:\Program Files\Java\jdk1.6.0_14\jre\bin\javaw" %JAVA_OPTS1% %JAVA_OPTS2% 
SET JAVASERVER_RUN=%JAVA_7HOME%\javaw %JAVA_OPTS1% %JAVA_OPTS2% 

REM SET R66HOME=D:\GG\R66Client\
REM SET R66BIN=%R66HOME%\lib

SET R66HOME=C:\SST24\WARP
SET R66BIN=%R66HOME%\lib
REM command for Client

REM Logger
SET LOGSERVER="-Dlogback.configurationFile=%R66HOME%\config\logback.xml"
SET LOGCLIENT="-Dlogback.configurationFile=%R66HOME%\config\logback-client.xml"

SET R66_CLASSPATH="%R66BIN%\WaarpR66-3.0.4.jar;%R66BIN%\*"

SET JAVARUNCLIENT=%JAVA_RUN% -cp %R66_CLASSPATH% %LOGCLIENT% -Dopenr66.locale=en -Dfile.encoding=UTF-8 
SET JAVARUNSERVER=%JAVASERVER_RUN% -cp %R66_CLASSPATH% %LOGSERVER% -Dopenr66.locale=en -Dfile.encoding=UTF-8 

REM SET SERVER_CONFIG="%R66HOME%/conf/config-serverA.xml"
REM SET CLIENT_CONFIG="%R66HOME%/conf/config-clientA.xml"

SET SERVER_CONFIG="%R66HOME%\config\Server.xml"
SET CLIENT_CONFIG="%R66HOME%\config\config-clientA.xml"
REM ################
REM # R66 COMMANDS #
REM ################

REM # SERVER SIDE #
REM ###############

REM # start the OpenR66 server
REM # no option
set R66SERVER=%JAVARUNSERVER% org.waarp.openr66.server.R66Server %SERVER_CONFIG%

REM # init database from argument
REM # [ -initdb ] [ -loadBusiness businessConfiguration ] [ -loadRoles roleConfiguration ] [ -loadAlias aliasConfig ] [ -dir rulesDirectory ] [ -limit xmlFileLimit ] [ -auth xmlFileAuthent ] [ -upgradeDb ]
set R66INIT=%JAVARUNCLIENT% org.waarp.openr66.server.ServerInitDatabase %SERVER_CONFIG%

REM # export configuration into directory
REM # directory
set R66CNFEXP=%JAVARUNCLIENT% org.waarp.openr66.server.ServerExportConfiguration %SERVER_CONFIG% 

REM PASSWORD Command line
set R66PASSGUI=%JAVARUNCLIENT% org.waarp.uip.WaarpUiPassword

REM ADMIN GUI
set R66ADMINGUI=%org.waarp.administrator.AdminGui

REM # export configuration as arguments
REM # [-hosts] [-rules] [-business ] [ -alias ] [ -roles ] [ -host host ]
set R66CONFEXP=%JAVARUNCLIENT% org.waarp.openr66.server.ConfigExport %SERVER_CONFIG% 

REM # import configuration as arguments
REM # [-hosts host-configuration-file] [-purgehosts] [-rules rule-configuration-file] [-purgerules] [-business file] [-purgebusiness] [-alias file] [-purgealias] [-roles file] [-purgeroles] [-hostid file transfer id] [-ruleid file transfer id] [-businessid file transfer id] [-aliasid file transfer id] [-roleid file transfer id] [-host host]
set R66CONFIMP=%JAVARUNCLIENT% org.waarp.openr66.server.ConfigImport %SERVER_CONFIG% 

REM # shutdown locally the server
REM # PID  optional PID of the server process
set R66SIGNAL="taskkill /T /PID "

REM # shutdown by network the server
REM # [-nossl|-ssl] default = -ssl
set R66SHUTD=%JAVARUNCLIENT% org.waarp.openr66.server.ServerShutdown %SERVER_CONFIG% 

REM # export the log
REM # [ -purge ] [ -clean ] [ -start timestamp ] [ -stop timestamp ] where timestamp are in yyyyMMddHHmmssSSS format eventually truncated and with possible ':- ' as separators
set R66EXPORT=%JAVARUNCLIENT% org.waarp.openr66.server.LogExport %SERVER_CONFIG% 

REM # export the log (extended)
REM # [-host host [-ruleDownload rule [-import]]] [ -purge ] [ -clean ] [-startid id] [-stopid id] [-rule rule] [-request host] [-pending] [-transfer] [-done] [-error] [ -start timestamp ] [ -stop timestamp ] where timestamp are in yyyyMMddHHmmssSSS format eventually truncated and with possible ':- ' as separators
set R66LOGEXPORT=%JAVARUNCLIENT% org.waarp.openr66.server.LogExtendedExport %SERVER_CONFIG% 

REM # import the log (should be used on another server)
REM # exportedLogFile
set R66LOGIMPORT=%JAVARUNCLIENT% org.waarp.openr66.server.LogImport %SERVER_CONFIG% 

REM # change limits of bandwidth
REM # "[ -wglob x ] [ -rglob w ] [ -wsess x ] [ -rsess x ]"
set R66LIMIT=%JAVARUNCLIENT% org.waarp.openr66.server.ChangeBandwidthLimits %SERVER_CONFIG% 

REM # Administrator Gui
REM # no argument
set R66ADMIN=%JAVARUNCLIENT% org.waarp.administrator.AdminGui %SERVER_CONFIG% 

REM # CLIENT SIDE #
REM ###############

REM # asynchronous transfer
REM # (-to hostId -file filepath -rule ruleId) | (-to hostId -id transferId) [ -md5 ] [ -block size ] [ -nolog ] [-start yyyyMMddHHmmssSSS | -delay +durationInMilliseconds | -delay preciseTimeInMilliseconds] [ -info "information" ]
set R66SEND=%JAVARUNCLIENT% org.waarp.openr66.client.SubmitTransfer %CLIENT_CONFIG% 

REM # synchronous transfer
REM # (-to hostId -file filepath -rule ruleId) | (-to hostId -id transferId) [ -md5 ] [ -block size ] [ -nolog ] [-start yyyyMMddHHmmssSSS | -delay +durationInMilliseconds | -delay preciseTimeInMilliseconds] [ -info "information" ]
set R66SYNCSEND=%JAVARUNCLIENT% org.waarp.openr66.client.DirectTransfer %CLIENT_CONFIG% 

REM # get information on transfers
REM # (-id transferId -to hostId as requested | -id transferId -from hostId as requester) 
REM # follow by one of: (-cancel | -stop | -restart [ -start yyyyMMddHHmmss | -delay +durationInMilliseconds | -delay preciseTimeInMilliseconds ]
set R66REQ=%JAVARUNCLIENT% org.waarp.openr66.client.RequestTransfer %CLIENT_CONFIG% 

REM # get information on remote files or directory
REM # "-to host -rule rule [ -file file ] [ -exist | -detail | -list | -mlsx ]
set R66INFO=%JAVARUNCLIENT% org.waarp.openr66.client.RequestInformation  %CLIENT_CONFIG% 

REM # test the connectivity
REM # -to host -msg "message"
set R66MESG=%JAVARUNCLIENT% org.waarp.openr66.client.Message %CLIENT_CONFIG% 

REM # Gui interface
REM # no argument
set R66GUI=%JAVARUNCLIENT% org.waarp.openr66.r66gui.R66ClientGui %CLIENT_CONFIG% 


REM # R66 Multiple Submit
REM # (-to hostId,hostID -file filepath,filepath -rule ruleId) | (-to hostId -id transferId) [ -md5 ] [ -block size ] [ -nolog ] [-start yyyyMMddHHmmssSSS | -delay +durationInMilliseconds | -delay preciseTimeInMilliseconds] [ -info "information" ]
set R66MULTISEND=%JAVARUNCLIENT% org.waarp.openr66.client.MultipleSubmitTransfer %CLIENT_CONFIG% 

REM # R66 Multiple synchronous transfer
REM # (-to hostId,hostid -file filepath,filepath -rule ruleId) | (-to hostId -id transferId) [ -md5 ] [ -block size ] [ -nolog ] [-start yyyyMMddHHmmssSSS | -delay +durationInMilliseconds | -delay preciseTimeInMilliseconds] [ -info "information" ]
set R66MULTISYNCSEND=%JAVARUNCLIENT% org.waarp.openr66.client.MultipleDirectTransfer %CLIENT_CONFIG% 


REM # R66 Spooled directory transfer launch with options as arguments
REM # (-to hostId,hostId -directory directory,directory -statusfile file -stopfile file -rule ruleId) [-name name] [-md5] [-block size] [-nolog ] [-elapse elapse] [-regex regex] [-submit|-direct [-parallel [-limitParallel limit]|-sequential]] [-recursive] [-info "information"] [-waarp hostId,hostId [-elapseWaarp elapse]]
set R66SPOOLEDSEND=%JAVARUNCLIENT% org.waarp.openr66.client.SpooledDirectoryTransfer %CLIENT_CONFIG% 
REM # R66 Spooled directory transfer launch with only xml configuration file as option with all configuration in it (SpooledConfiguration)
set R66SPOOLEDDEMON=%JAVARUNCLIENT% org.waarp.openr66.client.SpooledDirectoryTransfer 

this is the only file which i have modified.
Pls let me know , as am trying to do a research for my personal studies.

Regards,
Ronald

**Comment by fredericBregier** [comment]
Execute %R66ADMIN% to run the admin gui (or create your own admingui.bat as for R66CIGUI.bat), then you can edit your own configuration file, create the password, ...

To initiate the database: %R66INIT%  -initdb -dir yourconfigpathForRules (or again creating your own dbinit.bat)

Then to start the server, you can effectively run bin\server.bat

**Comment by ronea23** [comment]
![r66dbinit](https://cloud.githubusercontent.com/assets/10896354/9356588/71c758e2-469f-11e5-8c12-92db65696663.png)

only dbinit with table creation is successfull, no entries are found in the table..

Regards,
Ronald

**Comment by ronea23** [comment]
Hi,

What is the minimum jdk required to run this software.

How to call the configuration files ? am confused a bit. because the error message is very clean

org.waarp.common.database.exception.WaarpDatabaseNoDataException: No row found
	at org.waarp.openr66.database.data.DbHostAuth.select(DbHostAuth.java:508) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.database.data.DbHostAuth.<init>(DbHostAuth.java:365) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.context.authentication.R66Auth.getServerAuth(R66Auth.java:243) ~[WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2258) [WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.server.R66Server.initialize(R66Server.java:72) [WaarpR66-3.0.4.jar:na]
	at org.waarp.openr66.server.R66Server.main(R66Server.java:54) [WaarpR66-3.0.4.jar:na]
19/08/2015/16:32:54.951 ERROR [org.waarp.openr66.configuration.FileBasedConfiguration] [main] org.waarp.openr66.configuration.FileBasedConfiguration.setConfigurationServerFromXml(FileBasedConfiguration.java:2262) : Cannot find Authentication for current host

Is the configuration file should be called to run the server ?

Regards,
Ronald

**Comment by fredericBregier** [comment]
Minimum JDK is 1.6, but preferred is 1.7 or higher.
The configuration file contains the minimum information to start the server. However the database (if configured) must be also loaded with necessary informations, such as authentication, rules and so on.

So you have to load the configuration inside the database using the initdb.
Of course, if you use the default from the distribution but change the server name and so on, you need to create your server authentication, rules... and to load them.

After you did the initdb with the parameters (you can pass multiple parameters at once), you should have a non empty database.

**Comment by ronea23** [comment]
Am using jdk 1.7, have tried the server both on Linux and as well as Windows machines, the issue is same.
Either the configuration file is having issues or the local environment is having issues.

Let me update after some trials, let me see the end.

Regards,
Ronald

**Comment by fredericBregier** [comment]
Since you opened a new issue and no feedback from then, I suppose this can be close.
Fell free to reopen a new one for a specific issue. ;-)
