### ISSUE TITLE
Direct transfer

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#184]
Hi Frédéric,

I'm working on sending files via R66 protocol and using an application server.
I need to adapt the DirectTransfer main to remove the system.exit() but also to find an alternative to networkTransaction.closeAll() (which is triggering a shutdown hook causing the JVM to be killed after a timeout is reached and closing the database connection).
Here my business case :
I have some files received on the app server via various protocol and for each file received I'm triggering a direct transfer.

How should I do to
1) close the connection to the remote host after some timeout
2) reuse the existing connection the remote host (if already connected)
3) do not close the connection to the database for each transfer (linked to evolution demand of have a datasource/connection pool)

**Comment by fredericBregier** [comment]
You could have a look at MultipleDirectTransfer source code.

The main idea is to not use the "main" from DirectTransfer but to make new DirectTransfer(...) and calls the necessary commands on it (see run method of MultipleDirectTransfer).
Then in your application, you have an init as described in the main but in your "main" main, so not in the your class that implements the transfer.

Therefore system.exit() and networkTransaction.closeAll() is only called when "your" application is shutting down, not when the client is over (connection availability then still remains).
Then the rest of your questions is taken into account by the DirectTransfer code (not the main part).

**Comment by Astr0boy** [comment]
Yes sorry I really need some rest :)

**Comment by fredericBregier** [comment]
No issue ! Glad that it helps you !
