### ISSUE TITLE
REST API for submitting a transfer - pipes not closed ?

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#185]
Hi Frédéric,

I've implemented a R66 rest client based on the example org.waarp.openr66.protocol.http.rest.test.HttpTestRestR66Client but I'm experimenting some issues...
The client is working and the transfer is submitted, however after a number of transfers I'm having a java exception too many open files.
After looking at my JVM pid running the rest client, I can see that the number of open files is growing and I guess there's some pipes or something else not closed properly.
When the transfer is submitted, I'm using the WaarpSslUtility.closingSslChannel(channel) & clientHelper.closeAll() methods.
Do you have any clues ?

**Comment by fredericBregier** [comment]
For the moment, I don't have any clue. Note howver that HttpTestRestR66Client is a test program, not a "supported" program... That's could be the reason ;-)

**Comment by fredericBregier** [comment]
One idea: it is in link with how Netty is working.
Netty uses ThreadPool (which are initiated and closed respectively in constructor (NioEventLoopGroup)  and closeAll). In various OS, this brings extra "fake" open files, but counted as such by the OS. I have no control on that, but one can limit the impact by:

- specifying small number of threads (in general close to the number of "concurrent" clients, and for server parts the number of cores * 2) : in the HttpTestRestR66Client this is the nbclient parameter
- ensureing that you keep the bootstrap (and therefore its NioEventLoopGroup) over all call, meaning defining it once and reusing it all over (as in the HttpTestRestR66Client created in the constructor and reused over all threads)

So you should not create the bootstrap and ending it for each and every Rest client call, but once for all, then reusing the bootstrap already created.

I believe this is your issue.

**Comment by Astr0boy** [comment]
I'll investigate in that direction.
Thanks.
