### ISSUE TITLE
SSL certificate revocation

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#195]
Hi Frédéric,

At the moment, we got our signed certificates working with the double R66 proxy configuration. One thing that is still causing trouble, is certificate revocation. 

Clientside we have a keystore with  private key signed by customer root CA and a truststore with root CA public certificate.

Serverside and proxyside we have a keystore containing a private key defined with appropriate csr, and a truststore with root CA public certificate and client public certificates. 

We noticed that root CA must be in the truststore, otherwise ssl handshake doesn't work, but in this way, public client certificates are completely ignored (actually leaving in the server truststore, public client certificates only, doesn't work).

So the question is: how do we invalidate client certificates? Currently public client certificates have a distribution point list which is internet accessible, like this one:
<pre><code>
[DistributionPoint:
     [URIName: http://XXXX.XXXX.xx/CRL/ca.crl, URIName: ldap://XXXX.XXXX.xx/ou=xxxx,o
=xxxxx,c=IT?certificateRevocationList]
, DistributionPoint:
     [CN=XXX, OU=xxxxx, O=xxxxx, C=IT]
]
</code></pre>

we tried to check whether client and/or server queries those services, in order to verify client revocation with no luck...

Any thoughts on this?

Regards

Alex

**Comment by fredericBregier** [comment]
I'm not that good on certificate part. Maybe asking waarp support could help you ?

**Comment by alexbarta** [comment]
just sent, thanks.

**Comment by fredericBregier** [comment]
Another thread opened on info at waarp.fr so closing it
