### ISSUE TITLE
Database connection closed after 8 hours -> PrepareStatement are failing

### ISSUE THREAD

**Issue by Astr0boy** [waarp/WaarpR66#196]
After 8 hours of inactivity (no r66 transfers), I have some exceptions in the logs and the transfers are failing. I tried the autoReconnect option in the url but it's not working.
I didn't see any keep alive in the connection pool, so I guess the connection is closed after 8 hours.
Did you already have such feedback from other users ?

10/05/2016/16:18:10.173 ERROR [org.waarp.common.database.DbPreparedStatement] [ActiveMQ Session Task-7] org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230) : SQL Exception createPreparedStatement from jdbc:mysql://localhost:3306/srv0010?autoReconnect=true:SELECT HOSTIDS,MODETRANS,RECVPATH,SENDPATH,ARCHIVEPATH,WORKPATH,RPRETASKS,RPOSTTASKS,RERRORTASKS,SPRETASKS,SPOSTTASKS,SERRORTASKS,UPDATEDINFO,IDRULE FROM  RULES  WHERE IDRULE = ?  No operations allowed after connection closed.

**Comment by fredericBregier** [comment]
Internally the connection is tested and retried if necessary, see:

- https://github.com/waarp/WaarpCommon/blob/master/src/main/java/org/waarp/common/database/model/DbModelMysql.java#L148
- https://github.com/waarp/WaarpCommon/blob/master/src/main/java/org/waarp/common/database/DbConnectionPool.java#L50

However there could be other elements that prevent such retries.
As you probably think, such "long term" issue could be difficult to reproduce.
Is there any other errors before ?

**Comment by Astr0boy** [comment]
Here what I can see in the log. It really looks like the wait_timeout of MySQL instance is reached and no reconnection is done. I think the issue can be reproduce but setting a low value to wait_timeout parameter of MySQL (SET GLOBAL wait_timeout = X;SET GLOBAL interactive_timeout = X;)

10/05/2016/13:58:51.805 INFO [org.waarp.openr66.protocol.configuration.Configuration] [ScheduledTask-2] org.waarp.openr66.protocol.configuration.Configuration$CleanLruCache.run(Configuration.java:1319) : Clear Cache: 0
10/05/2016/14:01:29.504 INFO [org.waarp.openr66.protocol.configuration.Configuration] [ScheduledTask-2] org.waarp.openr66.protocol.configuration.Configuration$CleanLruCache.run(Configuration.java:1319) : Clear Cache: 0
10/05/2016/14:01:51.812 INFO [org.waarp.openr66.protocol.configuration.Configuration] [ScheduledTask-2] org.waarp.openr66.protocol.configuration.Configuration$CleanLruCache.run(Configuration.java:1319) : Clear Cache: 0
10/05/2016/14:03:30.809 ERROR [org.waarp.common.database.DbPreparedStatement] [ActiveMQ Session Task-5] org.waarp.common.database.DbPreparedStatement.executeQuery(DbPreparedStatement.java:282) : SQL Exception executeQuery:SELECT HOSTIDS,MODETRANS,RECVPATH,SENDPATH,ARCHIVEPATH,WORKPATH,RPRETASKS,RPOSTTASKS,RERRORTASKS,SPRETASKS,SPOSTTASKS,SERRORTASKS,UPDATEDINFO,IDRULE FROM  RULES  WHERE IDRULE = ?  The last packet successfully received from the server was 65 082 317 milliseconds ago.  The last packet sent successfully to the server was 65 082 317 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

**Comment by fredericBregier** [comment]
Connections are always tested (during exception at last and before too).
See for instance: 
- https://github.com/waarp/WaarpCommon/blob/master/src/main/java/org/waarp/common/database/DbPreparedStatement.java#L224
- https://github.com/waarp/WaarpCommon/blob/master/src/main/java/org/waarp/common/database/DbSession.java#L418
- https://github.com/waarp/WaarpCommon/blob/master/src/main/java/org/waarp/common/database/model/DbModelAbstract.java#L100

Of course, an error could be there, but as far as I see, the connection is tested first, then the transaction is made and if an error occurs, the connections is tested again and checked.

WYDT?

**Comment by Astr0boy** [comment]
Thanks Frédéric. Yes, this is what I see also in the code.
Then the issue should be somewhere in my code, I need to investigate, I'll update the issue with my findings. In my java class, I'm extending AbstractTransfer, I might have forgotten somewhere a test.

**Comment by Astr0boy** [comment]
I can confirm that when the wait_timeout is reached (at least in some cases) the reconnection to the db is not working.
Here how I proceed:

1) Set MySQL wait_timeout &  interactive_timeout to 5 minutes
SET GLOBAL wait_timeout=300;
SET GLOBAL interactive_timeout=300;

2) Connect to R66-Web-Administration (I'm using the static version)

3) Wait for at least 5 minutes

4) Search for a rule and a transfer

5) I can see the following errors in the log:

16/05/2016/11:57:37.352 INFO [org.waarp.openr66.protocol.configuration.Configuration] [ScheduledTask-5] org.waarp.openr66.protocol.configuration.Configuration$CleanLruCache.run(Configuration.java:1319) : Clear Cache: 0
16/05/2016/11:57:53.445 INFO [org.waarp.openr66.protocol.configuration.Configuration] [ScheduledTask-5] org.waarp.openr66.protocol.configuration.Configuration$CleanLruCache.run(Configuration.java:2376) : Clear Cache: 0
16/05/2016/11:58:03.620 ERROR [org.waarp.common.database.DbPreparedStatement] [HttpWorker-11] org.waarp.common.database.DbPreparedStatement.executeQuery(DbPreparedStatement.java:282) : SQL Exception executeQuery:SELECT HOSTIDS,MODETRANS,RECVPATH,SENDPATH,ARCHIVEPATH,WORKPATH,RPRETASKS,RPOSTTASKS,RERRORTASKS,SPRETASKS,SPOSTTASKS,SERRORTASKS,UPDATEDINFO,IDRULE FROM  RULES  ORDER BY IDRULE Communications link failure

The last packet successfully received from the server was 463,190 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
16/05/2016/11:58:03.620 ERROR [org.waarp.common.database.DbSession] [HttpWorker-11] org.waarp.common.database.DbSession.error(DbSession.java:255) : SQLException: Communications link failure

The last packet successfully received from the server was 463,190 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago. SQLState: 08S01VendorError: 0
16/05/2016/11:58:03.620 WARN [org.waarp.openr66.protocol.http.adminssl.HttpSslHandler] [HttpWorker-11] org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.createExport(HttpSslHandler.java:1233) : OpenR66 Web Error SQL Exception executeQuery: SELECT HOSTIDS,MODETRANS,RECVPATH,SENDPATH,ARCHIVEPATH,WORKPATH,RPRETASKS,RPOSTTASKS,RERRORTASKS,SPRETASKS,SPOSTTASKS,SERRORTASKS,UPDATEDINFO,IDRULE FROM  RULES  ORDER BY IDRULE
16/05/2016/11:58:10.778 ERROR [org.waarp.common.database.DbPreparedStatement] [HttpWorker-11] org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230) : SQL Exception createPreparedStatement from jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT BUSINESS,ROLES,ALIASES,OTHERS,UPDATEDINFO,HOSTID FROM  HOSTCONFIG  WHERE HOSTID = ?  No operations allowed after connection closed.
16/05/2016/11:58:10.778 ERROR [org.waarp.common.database.DbSession] [HttpWorker-11] org.waarp.common.database.DbSession.error(DbSession.java:255) : SQLException: No operations allowed after connection closed. SQLState: 08003VendorError: 0
16/05/2016/11:58:10.778 ERROR [org.waarp.common.database.DbPreparedStatement] [HttpWorker-11] org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230) : SQL Exception createPreparedStatement from jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48 No operations allowed after connection closed.
16/05/2016/11:58:10.778 ERROR [org.waarp.common.database.DbSession] [HttpWorker-11] org.waarp.common.database.DbSession.error(DbSession.java:255) : SQLException: No operations allowed after connection closed. SQLState: 08003VendorError: 0
16/05/2016/11:58:10.778 WARN [org.waarp.openr66.protocol.http.adminssl.HttpSslHandler] [HttpWorker-11] org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.Listing(HttpSslHandler.java:477) : OpenR66 Web Error SQL Exception createPreparedStatement: SELECT GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48

**Comment by bcarlin** [comment]
A beta distribution cotaining a fix for this bug is available here : https://discuss.waarp.org/t/release-of-waarp-r66-3-0-7-beta1/17

Can you please try again with this fix ?

**Comment by Astr0boy** [comment]
Hi Bruno,

I did some new tests but I have the same error. I guess something was fixed
also on Waarp Common ?

2016-06-29 18:42 GMT+02:00 Bruno Carlin <notifications@github.com>:

**Comment by bcarlin** [comment]
Yes, the fix is in Waarp Common, wich is included in the package ;)

**Comment by Astr0boy** [comment]
Saw that after I post the comment :)
I did some more test but the error is still showing:

05/07/2016/16:10:14.873 ERROR
[org.waarp.common.database.DbPreparedStatement]
org.waarp.common.database.DbPreparedStatement.executeQuery(DbPreparedStatement.java:282)
: SQL Exception executeQuery:SELECT
BUSINESS,ROLES,ALIASES,OTHERS,UPDATEDINFO,HOSTID FROM  HOSTCONFIG  WHERE
HOSTID = ?  Communications link failure

The last packet successfully received from the server was 907,619
milliseconds ago.  The last packet sent successfully to the server was 8
milliseconds ago.
05/07/2016/16:10:14.874 ERROR [org.waarp.common.database.DbSession]
org.waarp.common.database.DbSession.error(DbSession.java:251) :
SQLException: Communications link failure

The last packet successfully received from the server was 907,619
milliseconds ago.  The last packet sent successfully to the server was 8
milliseconds ago. SQLState: 08S01VendorError: 0
05/07/2016/16:10:14.875 ERROR
[org.waarp.common.database.DbPreparedStatement]
org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230)
: SQL Exception createPreparedStatement from
jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT
GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID
FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48
No operations allowed after connection closed.
05/07/2016/16:10:14.875 ERROR [org.waarp.common.database.DbSession]
org.waarp.common.database.DbSession.error(DbSession.java:251) :
SQLException: No operations allowed after connection closed. SQLState:
08003VendorError: 0
05/07/2016/16:10:14.875 WARN
[org.waarp.openr66.protocol.http.adminssl.HttpSslHandler]
org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.Listing(HttpSslHandler.java:477)
: OpenR66 Web Error SQL Exception createPreparedStatement: SELECT
GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID
FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48
05/07/2016/16:10:18.824 ERROR
[org.waarp.common.database.DbPreparedStatement]
org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230)
: SQL Exception createPreparedStatement from
jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT
ADDRESS,PORT,ISSSL,HOSTKEY,ADMINROLE,ISCLIENT,ISACTIVE,ISPROXIFIED,UPDATEDINFO,HOSTID
FROM  HOSTS  WHERE ISSSL = ? AND ISACTIVE = ?  ORDER BY HOSTID No
operations allowed after connection closed.
05/07/2016/16:10:18.824 ERROR [org.waarp.common.database.DbSession]
org.waarp.common.database.DbSession.error(DbSession.java:251) :
SQLException: No operations allowed after connection closed. SQLState:
08003VendorError: 0
05/07/2016/16:10:18.824 WARN
[org.waarp.openr66.protocol.http.adminssl.HttpSslHandler]
org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.Hosts(HttpSslHandler.java:1056)
: OpenR66 Web Error SQL Exception createPreparedStatement: SELECT
ADDRESS,PORT,ISSSL,HOSTKEY,ADMINROLE,ISCLIENT,ISACTIVE,ISPROXIFIED,UPDATEDINFO,HOSTID
FROM  HOSTS  WHERE ISSSL = ? AND ISACTIVE = ?  ORDER BY HOSTID
05/07/2016/16:10:35.979 ERROR
[org.waarp.common.database.DbPreparedStatement]
org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230)
: SQL Exception createPreparedStatement from
jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT
BUSINESS,ROLES,ALIASES,OTHERS,UPDATEDINFO,HOSTID FROM  HOSTCONFIG  WHERE
HOSTID = ?  No operations allowed after connection closed.
05/07/2016/16:10:35.980 ERROR [org.waarp.common.database.DbSession]
org.waarp.common.database.DbSession.error(DbSession.java:251) :
SQLException: No operations allowed after connection closed. SQLState:
08003VendorError: 0
05/07/2016/16:10:35.980 ERROR
[org.waarp.common.database.DbPreparedStatement]
org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:230)
: SQL Exception createPreparedStatement from
jdbc:mysql://localhost:3306/test?autoReconnect=true:SELECT
GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID
FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48
No operations allowed after connection closed.
05/07/2016/16:10:35.980 ERROR [org.waarp.common.database.DbSession]
org.waarp.common.database.DbSession.error(DbSession.java:251) :
SQLException: No operations allowed after connection closed. SQLState:
08003VendorError: 0
05/07/2016/16:10:35.980 WARN
[org.waarp.openr66.protocol.http.adminssl.HttpSslHandler]
org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.Listing(HttpSslHandler.java:477)
: OpenR66 Web Error SQL Exception createPreparedStatement: SELECT
GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID
FROM  RUNNER  WHERE  OWNERREQ = 'opx'  ORDER BY STARTTRANS DESC  LIMIT 48

**Comment by bcarlin** [comment]
the work now continues in #234 (this ticket regroups all problems about database connections...)
