### ISSUE TITLE
Compatibility beetween differents version of waarp

### ISSUE THREAD

**Issue by cedricconstans** [waarp/WaarpR66#199]
Hi,

Do you know if it's possible to do transfert beetween two waarp which are not on the same version ?
For example beetween waarp 2.4 and waarp 3.0.5 ? Are they technicals particularities ?

Thanks for your response.

Best regards

**Comment by bcarlin** [comment]
Hi,
it should work!

**Comment by cedricconstans** [comment]
Hi,
Thanks. But I test it and I've got an error when I'm doing "Test Connection" with 2.4 version (I'm testing connection to an 3.0.5 version)

![400](https://cloud.githubusercontent.com/assets/19839653/15958769/c255aa3e-2ef7-11e6-8f7f-f89d76ee267d.jpg)

In the logs we can see 
10:28:04.498 [Hashed wheel timer #1] INFO  o.w.o.p.n.NetworkTransaction - org.waarp.openr66.protocol.networkhandler.NetworkTransaction$CloseFutureChannel.run(NetworkTransaction.java:900) : Will close NETWORK
 channel
10:28:05.447 [Hashed wheel timer #1] INFO  o.w.o.p.n.NetworkTransaction - org.waarp.openr66.protocol.networkhandler.NetworkTransaction$CloseFutureChannel.run(NetworkTransaction.java:900) : Will close NETWORK
 channel
10:32:30.341 [LocalExecutor-151] INFO  org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.useConnection(DbSession.java:322) : ThreadUsing: 1
10:33:00.560 [HttpExecutor-95] ERROR o.w.o.p.e.OpenR66ExceptionTrappedFactory - org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory.getExceptionFromTrappedException(OpenR66ExceptionTrappedFac
tory.java:127) : Null pointer Exception
java.lang.NullPointerException: null
        at org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.Hosts(HttpSslHandler.java:1041) ~[WaarpR66-2.4.10.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.messageReceived(HttpSslHandler.java:1773) ~[WaarpR66-2.4.10.jar:na]
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[netty-3.5.8.Final.jar:na]
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:45) [netty-3.5.8.Final.jar:na]
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69) [netty-3.5.8.Final.jar:na]
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:315) [netty-3.5.8.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:896) [na:6.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:6.0]
        at java.lang.Thread.run(Thread.java:735) [na:6.0]
10:33:00.561 [HttpExecutor-95] WARN  o.w.o.p.http.adminssl.HttpSslHandler - org.waarp.openr66.protocol.http.adminssl.HttpSslHandler.exceptionCaught(HttpSslHandler.java:1946) : Exception in HttpSslHandler Nul
l Pointer Exception
10:33:00.738 [HttpExecutor-95] INFO  org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:363) : Current cached connection: 1
10:33:30.399 [Hashed wheel timer #1] INFO  o.w.o.p.n.NetworkServerHandler - org.waarp.openr66.protocol.networkhandler.NetworkServerHandler.channelIdle(NetworkServerHandler.java:180) : Write KAlive
10:33:30.958 [ServerExecutor-176] WARN  org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:351) : Still some clients could use this Database Session: 1
10:33:30.959 [ServerExecutor-176] INFO  org.waarp.common.database.DbSession - org.waarp.common.database.DbSession.disconnect(DbSession.java:363) : Current cached connection: 0

Do you know if it's a product bug o if seems to be an environnement problem ?

Thanks

Best regards

**Comment by maximeRobert** [comment]
Hi,

I wasn't able to reproduce your error with WaarpR66-2.4.34.
Maybe you should concider updating your version.

Thanks

Best regards

**Comment by cedricconstans** [comment]
Hi,

Thanks for your response.

I try with 2.4.9 -> 3.0.5

Best regards

**Comment by bcarlin** [comment]
It turns out there are incompatibilities between Waarp R66 before and after 2.4.10. We are currently working on that issue.

**Comment by bcarlin** [comment]
Fixing this issue asks for protocol change that are not possible in version 2.4.10 and earlier (the breaking change is precisely adding possibilities to evolve the protocol without braking things).
