### ISSUE TITLE
Avoid modifying scripts for path to ENV_R66

### ISSUE THREAD

**Issue by MichaelReicheOracle** [waarp/WaarpR66#207]
You can avoid modifying the shell scripts for the path to ENV_66 like this ;

echo Start R66Command
# Change path if necesary
SCRIPT=$(readlink -f $(which "$0"))   # some people recommend using 'readlink' (which also requires the use of 'which')
DIR=$(dirname "$SCRIPT")  # if you don't use readlink you could just use $0 here instead of $SCRIPT
. $DIR/../ENV_R66
.
.
.

**Comment by MichaelReicheOracle** [comment]
Also - if you rely  on the standard $JAVA_HOME variable, ENV_R66 won't need to be modified for the location of Java...

 export JAVABASE="$JAVA_HOME"

And you could also determine R66HOME from the relative location of the SCRIPT.

**Comment by fredericBregier** [comment]
nice proposal! Thanks!!!
@bcarlin good idea, isn't it ?

**Comment by bcarlin** [comment]
it's a good idea!
We are actually preparing a new distribution of Waarp R66. We rely on that to achieve portability.
Though not complete yet, we will start to ship this new distribution with next version.

Is it necessary to change ENV_R66 as well ?

**Comment by marakiis** [comment]
The new packaging (Waarp 3.0.9) solve this issue.
