### ISSUE TITLE
REST API - Insert new host

### ISSUE THREAD

**Issue by charbonnier666** [waarp/WaarpR66#214]
Inserting a new host with a body like this:

```
{
	"ADDRESS": "123",
	"PORT": 123,
	"ISSSL": 0,	
"HOSTKEY":null,
	"ADMINROLE":0,
	"ISCLIENT":0,
	"ISACTIVE": 0,
	"ISPROXIFIED":0,
	"UPDATEDINFO":0,
	"HOSTID": "BLABLA-1"
}
```

I got this error on server:

> .....WaarpDatabaseSqlException: Not enough argument to create the object.....

**Comment by fredericBregier** [comment]
HOSTKEY must not be empty or null, as HOSTID and ADDRESS.

That is the source of your issue.
