### ISSUE TITLE
Is it possible to force positive transferid integers?

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#224]
Hi @fredericBregier , @bcarlin 

handling dashes  at the beginning of a filename is very annoying, in bash for example, moving a file with such name does not work:

```
mv  -9223372036854775768_6459670090292664973_file.txt.r66
```

Is there a way to force positive id generation via waarp?

Regards

Alex

**Comment by bcarlin** [comment]
Waarp R66 uses in part database autoincrements (at least for the part starting with a minus) as transfer ids, starting the sequence at the lowest allowed value (-2^63 + 1).
You can just reset the sequence at 0 or 1 in your database (the sequence is named runseq) to only have positive ids.

**Comment by alexbarta** [comment]
Thanks! I'll try and report back here

Alex

**Comment by alexbarta** [comment]
Hi Bruno,

I set Seq parameter as 1000000000000000000 just to have same id char length. Do you see any drawbacks ? (I don't know if reducing the id range may compromise the uniqueness of the id in waarp...)

**Comment by bcarlin** [comment]
I do not see why it would be a problem...

**Comment by alexbarta** [comment]
ok thanks, I think you may close this one
