### ISSUE TITLE
Handling white spaces in R66 transfer

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#225]
Hi @fredericBregier , @bcarlin 

R66 seems not handle white spaces correctly. For example when I generate a file (example below) and do r66multisyncsend '*.txt' :

```
echo 1 > test\ test.txt
``` 

when I do MOVERENAME to #ORIGINALFILENAME#  results into a truncated filename to first whitespace:

```
test
``` 

Any advice on this ?

Thanks,

Regards

Alex

**Comment by bcarlin** [comment]
I'm afraid that MOVERENAME as well as all File manipulation programs (COPY, COPYRENAME, etc...)
are affected by this. 
The parser for path is too naïve to handle whitespaces like that.

There should be an escape mechanism for that (for example quotes: `"me file.txt"`).

I think there might be, however, a quick fix for your case: the whitespace is introduced with the substitution of `#ORIGINALFILENAME#`. 
I'll look into that.

**Comment by alexbarta** [comment]
Any news on this one?

Regards

Alex
