### ISSUE TITLE
How do I insert '>' or '>>' redirects in rule tasks ?

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#227]
Hi,

I have tried to redirect command's output to file in EXEC tasks using '>' and '>>' but didn't  succeed.
I tried '&gt;' but didn't work either.

Any advice?

Best

Alex

**Comment by bcarlin** [comment]
EXEC and all similar commands (EXECOUTPUT, EXECRENAME) are not regular shells.
Their path field must be an executable (it will be searched in the system PATH, or you can give an absolute path) followed by arguments *separated by spaces*.
It means that redirections and pipes and backgrounding processes **will not** work.

to redirect the output, you should put it in a script, and put that script in the EXEC task

**Comment by alexbarta** [comment]
Ok clear! Thanks
