### ISSUE TITLE
REST CreateTransfer command issue

### ISSUE THREAD

**Issue by bertrandolg** [waarp/WaarpR66#229]
Hi,

I'm having trouble with the CreateTransfer REST command (Waarp R66 3.0.7). I'm currently testing it with Curl as this : 

`curl  -d'{"@class":"org.waarp.openr66.protocol.localhandler.packet.json.TransferRequestJsonPacket", "comment" : "Transfer Request (POST)","requestUserPacket" : 7, "rulename" : "rule1", "mode" : 0, "filename" : "/tmp/testfile", "requested" : "10.0.0.2", "blocksize" : 0,"rank" : 0, "specialId" : 0, "validate" : 0, "originalSize" : 0, "fileInformation" : "File information", "separator" : "{","start" : 1399760601381, "delay" : 0, "toValidate" : true, "additionalDelay" : false}' 'http://127.0.0.1:8088/control/'`

R66Server answer is : 

> org.waarp.gateway.kernel.exception.HttpIncorrectRequestException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "value": org.waarp.common.database.data.DbValue#setValue(1 params) vs org.waarp.common.database.data.DbValue#setValue(1 params)

Could you tell me if there's a missing argument into my request ?

Best regards.

**Comment by bcarlin** [comment]
Your command is actually right! This was a bug.

However, to make it easier for you, your query only needs a minimum of 4 arguments:

~~~json
{
    "@class": "org.waarp.openr66.protocol.localhandler.packet.json.TransferRequestJsonPacket",
    "rulename": "rule1",  
    "filename": "/tmp/testfile", 
    "requested": "10.0.0.2"
}
~~~
