### ISSUE TITLE
Monitoring bandwidth issue

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#244]
Hi @bcarlin,

I have noticed some anomalies with OutBandwidth/InBandwidth that didn't make this variable comparable with average transfer speed (file size/seconds elapsed). Looks that netty trafficCounter is erroneously shifted by 7 in B/s -> KB/s transformation and not by 10 as it should.
I did modify myself the shift from >> 7 to >> 10 and actually obtained correct value this time
 
https://github.com/waarp/WaarpR66/blob/4a17c3e8f802b7ea60197d63a3352c39c57c50b1/src/main/java/org/waarp/openr66/protocol/localhandler/Monitoring.java#L382

https://github.com/waarp/WaarpR66/blob/4a17c3e8f802b7ea60197d63a3352c39c57c50b1/src/main/java/org/waarp/openr66/protocol/localhandler/Monitoring.java#L383

https://github.com/waarp/WaarpR66/blob/4a17c3e8f802b7ea60197d63a3352c39c57c50b1/src/main/java/org/waarp/openr66/protocol/localhandler/Monitoring.java#L406

https://github.com/waarp/WaarpR66/blob/4a17c3e8f802b7ea60197d63a3352c39c57c50b1/src/main/java/org/waarp/openr66/protocol/localhandler/Monitoring.java#L407

Regards

**Comment by bcarlin** [comment]
I do not see any issue here.
Bandwidths are given in kilobits per second (`Kb/s`) while `trafficCounter.last{Read,Write}Throughput()` is in bytes (`B`) as the comment says (`// B/s -> Kb/s`)

The `>> 7` conversion does two things: convert bytes in bits (`* 8` or `<< 3`) and bits to kilobits (`/ 1024` or `>> 10`).
