### ISSUE TITLE
Multiple regex in r66multisyncsend

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#245]
Hi @fredericBregier , @bcarlin 
Is it possible to specify multiple regexe in the same r66 send command? Like -file "*.xml" and "*.txt"

Regards

Alex

**Comment by bcarlin** [comment]
Hi,

Though the patterns used for -file are not strictly regexes (it is more the expansion of * and ? symbols to substitute several or one characters), this arguments can accept multiple patterns separated by a comma (,).
